name: personal_expenses
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  dynamic_color: ^1.6.2
  flutter:
    sdk: flutter
  intl: ^0.18.0
  lottie: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  icons_launcher: ^2.1.0


flutter:
  uses-material-design: true

  assets:  # Lists assets, such as image files
    - assets/images/404.gif
    - assets/robot.json

  fonts:
    - family: Source Code Pro
      fonts:
        - asset: assets/fonts/SourceCodePro-Regular.ttf
        - asset: assets/fonts/SourceCodePro-VariableFont_wght.ttf

